# Generated by Django 5.1.3 on 2025-05-17 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lunchmap', '0003_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='author',
        ),
    ]
